import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import InputField from "@/components/InputField";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen">
        <div className=" grid place-items-center">
          <form
            className="w-3/4 bg-white p-20 rounded-md h-5/6 pb-24"
            action="#"
          >
            <div className="mb-10 flex flex-col justify-center">
              <h1 className="text-3xl font-bold text-center mb-4 ">Login</h1>
              <span className="text-zinc-400 text-center w-full">
                Please provide your credentials below
              </span>
            </div>
            <div>
              <p className="flex flex-col my-5">
                <InputField
                  entryValue={email}
                  updateEntryFunction={setEmail}
                  inputType="email"
                  label="Email"
                />
              </p>
              <p className="flex flex-col my-5">
                <InputField
                  entryValue={password}
                  updateEntryFunction={setPassword}
                  inputType="passowrd"
                  label="Password"
                />
              </p>
              <p className="flex flex-col my-5">
                <Link
                  className=" text-sm text-center bg-blue-500 py-2 text-white rounded-md "
                  href="/orders/list"
                >
                  Login
                </Link>
              </p>
            </div>
          </form>
        </div>
      </main>
    </>
  );
}
